### ISSUE TITLE
semver.satisfies(): '*' doesn't match prerelease identifiers 

### ISSUE THREAD

**Issue by myndzi** [npm/node-semver#130]
`semver.satisfies('0.3.16-foo.1', '*')` -> `false`

**Comment by megawac** [comment]
See https://github.com/npm/node-semver/issues/123

**Comment by myndzi** [comment]
Even after browsing that issue, it is unclear to me why a specifier that literally means "anything" should not match... well, anything. Additionally, it appears that there is no way, then, to construct such a comparison?

**Comment by isaacs** [comment]
@myndzi The principle at work here is that `0.3.16-foo.1` is a "prerelease" version.  Prereleases can include breaking changes at any time, and frequently don't even satisfy the API contracts inherent in a module, so they're excluded from any ranges that don't explicitly opt-in to a pre-release version in that chain.  So, for example, it *would* match `~0.3.16-alpha`, but that range would *not* be satisfied by `0.3.17-foo.1`, because that is a prerelease of a different version.

**Comment by myndzi** [comment]
I can understand this, to an extent, in the context of a partial version (say, `1.*`), but `*` is literally "everything", so how can anything fall "outside" this range?

**Comment by myndzi** [comment]
More importantly, I guess, it seems that the ability to opt in to or out of prerelease matches should more properly be an option passed to the `semver.satisfies` function, so that the user can control the behavior, rather than a forced behavior that only satisfies one of two needs...

**Comment by isaacs** [comment]
Having an option to allow prerelease matches against non-prerelease version ranges would be fine.  It'd be tricky to get the API right, though, especially since there's already one boolean and adding another one edges a bit too far down the slippery slope of long function signatures.  Maybe it'd be ok to replace the `loose` params with an options object, or have `loose` matches also allow prerelease versions to match against ranges?

**Comment by qzb** [comment]
In my opinion new x-ranges for prerelease versions would be a good idea. For example ``1.3.*-*`` should match to all prereleases  of ``1.3.*``, and ``* || *-*`` to any version at all (prerelease or not).
