### ISSUE TITLE
Spaces in hyphen ranges

### ISSUE THREAD

**Issue by smolyakoff** [npm/node-semver#138]
Do spaces in hyphen ranges matter? 
```js
semver.satisfies('1.2.0', '1.2.0-1.2.1'); // -> false
semver.satisfies('1.2.0', '1.2.0 - 1.2.1'); // -> true
semver.validRange('1.2.0-1.2.1'); // -> true
```

**Comment by isaacs** [comment]
Yes, they matter.

`1.2.0-1.2.1` is a valid SemVer version.

```
> semver.parse('1.2.0-1.2.1')
SemVer {
  loose: undefined,
  raw: '1.2.0-1.2.1',
  major: 1,
  minor: 2,
  patch: 0,
  prerelease: [ 1, 2, 1 ],
  build: [],
  version: '1.2.0-1.2.1' }
```

Because any version is a valid range (a range with exactly one satisfying version), it's different.  `1.2.0-1.2.1` won't match `1.2.0` or `1.2.1`.

**Comment by gravis** [comment]
I don't agree. Semver is stating: 

"Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]." 

Therefore, `1.2.1` is not a valid identifier, so there's no confusion about `1.2.0-1.2.1` being a hyphen range.

Thanks

**Comment by gravis** [comment]
Maybe the readme should be updated then, to precise that?

**Comment by isaacs** [comment]
You're taking section 9 of the http://semver.org spec out of context.  The `prerelease` section is a collection of period-separated identifiers.  Those identifiers can contain only ascii alphanumerics and hyphen.

So, you have the major `1`, then the minor `2`, then the patch `0`.  Then a hyphen, which introduces the prerelease section, `1.2.1`.  That section is a period-separated collection of identifiers.  First identifier is `1`, second is `2`, third is `1`, and that's it.

Since the readme already includes the semver.org spec by reference, I'd rather not copy it all here.

**Comment by isaacs** [comment]
Note that these are also valid semver versions: `1.2.3-4.5.6.7.8.9.0` or `1.2.3-4.5`.

**Comment by gravis** [comment]
Thanks for the clarification!
