### ISSUE TITLE
Prerelease Tags problem

### ISSUE THREAD

**Issue by fundon** [npm/node-semver#139]
```sh
# semver 5.0.3

semver 0.12.0 -r ' >= 0.9 < 1'
# => 0.12.0

semver 0.12.0-rc.0 -r ' >= 0.9 < 1'
# => not match
```

Whay not match?

**Comment by isaacs** [comment]
Working as designed.  It's explained in the docs here: https://github.com/npm/node-semver#prerelease-tags

Basically, since the semver.org spec says that prerelease tags can be breaking, you only get them if the range specifically opts into getting prereleases of that specific {major, minor, patch} tuple.
