### ISSUE TITLE
Underspecified

### ISSUE THREAD

**Issue by pkriens** [npm/node-semver#140]
I am trying to implement the rules in Java and find that the specification is rather underspecified. It would be nice to have a nice real classic BNF.

X-Ranges seem to act weird (I actually had not expected that you could use X-ranges when you specified a primitive version)

     semver 1.0.0 -r ">=1.x.1"                ok?
     semver 1.0.0 -r ">=1.x.1-foo"          ok?
     semver 1.0.0 -r "1.x.x - 2"               ok?

I can repeat primitives, caret and tildes but not hyphens:

     semver 1.0.0 -r ">=1 >=1 >=1"       ok
     semver 1.0.0 -r "1 - 2 "                    ok
     semver 1.0.0 -r "1 - 2 >=1"              false?

I can use X-Ranges on tilde and carets. Not sure what this means:

    semver 1.0.0 -r "~1.x.x"                   ok?
    semver 1.0.0 -r "^1.x.x"                   ok?

There is an ambiguity between a x-range and a default equal

    semver 1.0.0 -r "1.x.x"                   ok, x-range
    semver 1.0.0 -r "=1.x.x"                 ok? 

This is the BNF I came up with that you use now to reflect the current syntax:

    range-set ::= range ( '||' range ) *
    range       ::= hyphen | simple +
    hyphen     ::= partial '-' partial
    simple      ::= primitive | partial | tilde | caret
    primitive   ::= ( '<' | '>' | '>=' | '<=' | '=' | ) partial
    partial      ::= xr ( '.' xr ( '.' xr qualifier ? )? )?
    xr             ::= 'x' | 'X' | '*' | nr
    nr             ::= '0' | ['1'-'9']['0'-'9']+
    tilde          ::= '~' partial
    caret         ::= '^' partial
    qualifier    ::= ( '-' pre )? ( '+' build )?
    pre           ::= parts
    build         ::= parts
    part          ::= part ( '.' part ) *
    part          ::= nr | [-0-9A-Za-z]+

My assumption and recommendation is that for primitive, tilde, and caret the partial is invalid (at least with 'x' or '*') and should be a proper version

**Comment by isaacs** [comment]
Hi, sorry for my delay.

```
 semver 1.0.0 -r ">=1.x.1"                ok?
 semver 1.0.0 -r ">=1.x.1-foo"          ok?
 semver 1.0.0 -r "1.x.x - 2"               ok?
```

This is an interesting edge case that is not "officially" supported by the spec (such as it is), but does have a de-facto behavior that perhaps we ought to just define explicitly rather than change.

The first `x` that is encountered in a range prevents it from even bothering to parse the rest of it.  So, `1.x.2-foo` is functionally equivalent to simply `1.x`.

Observe:

```
> semver.Range('1.x.2')
Range {
  loose: undefined,
  raw: '1.x.2',
  set: [ [ [Object], [Object] ] ],
  range: '>=1.0.0 <2.0.0' }
> semver.Range('1.x')
Range {
  loose: undefined,
  raw: '1.x',
  set: [ [ [Object], [Object] ] ],
  range: '>=1.0.0 <2.0.0' }
```

The only difference is their "raw" field.  The first `x` effectively truncates the rest of the range, so `1.x.x` is functionally the same as `1` or `1.x`.  People just like putting the `x` there for some reason.

When you use greater-than/less-than operators, it also changes things.
```
> ['>','>=','=','<','<='].forEach(function(g) { var y = g + '1.x'; console.log('%s%s%s', y, new Array(12-y.length).join(' '), semver.Range(y).range) })
>1.x       >=2.0.0
>=1.x      >=1.0.0
=1.x       >=1.0.0 <2.0.0
<1.x       <1.0.0
<=1.x      <2.0.0
undefined
> ['>','>=','=','<','<='].forEach(function(g) { var y = g + '1.2.x'; console.log('%s%s%s', y, new Array(12-y.length).join(' '), semver.Range(y).range) })
>1.2.x     >=1.3.0
>=1.2.x    >=1.2.0
=1.2.x     >=1.2.0 <1.3.0
<1.2.x     <1.2.0
<=1.2.x    <1.3.0
```

So, in effect, when you do `>1.x`, you're saying "I want something that is greater than any `1.x` range", or in other words, `>=2.0.0`.

You can join the simpler "comparator plus version" style ranges (greater-than/less-than, tilde, caret, and partial/x-ranges) using a space, which is a logical "and" or "intersection" operator.  However, hyphen-ranges are more complicated, and can't be joined with a space to another range comparator.

So, you can do `1.2.3 - 2.x`, but you can't then join that to a `2.5.x` using a space.  It would not often be very useful anyway; you'd be saying "I want something between 1.2.3 and 2.x, and it has to also match 2.5.x".

You _can_ join hyphen ranges to other comparators using a `||`, which is a logical "or" or "union" operator.  `1.2.3 - 2.x || >=3.5.x <5` is allowed, and reasonable.  (Maybe there was a bug in the 3.x series that was fixed in 3.5 or something, and 5 isn't out yet, but we expect big changes.)

I'd love to add clearer specs for this.  I made a few slight tweaks to the BNF you provided here, which I think is the intended allowed behavior.  What do you think?

```bnf
range-set  ::= range ( logical-or range ) *
logical-or ::= ( ' ' ) * '||' ( ' ' ) *
range      ::= hyphen | simple ( ' ' simple ) * | ''
hyphen     ::= partial ' - ' partial
simple     ::= primitive | partial | tilde | caret
primitive  ::= ( '<' | '>' | '>=' | '<=' | '=' | ) partial
partial    ::= xr ( '.' xr ( '.' xr qualifier ? )? )?
xr         ::= 'x' | 'X' | '*' | nr
nr         ::= '0' | ['1'-'9']['0'-'9']+
tilde      ::= '~' partial
caret      ::= '^' partial
qualifier  ::= ( '-' pre )? ( '+' build )?
pre        ::= parts
build      ::= parts
parts      ::= part ( '.' part ) *
part       ::= nr | [-0-9A-Za-z]+
```

**Comment by pkriens** [comment]
Such a BNF would have saved me a lot of time. :-)

If ranges that have a value after an x are not valid, then I think the range should be marked as invalid. In general you want to catch errors early. (Though this is an interesting philosophical difference between Javascript & Java I've noticed :-)

About spaces, in general I prefer to define the behavior of whitespace to be explained outside the BNF grammar unless a space has a literal meaning. In general tokens are parsed by a lexer before fed to a grammar so in almost all cases the lexer handles the whitespaces anyway. And grammars tend to get very messy when you include whitespace rules.

**Comment by isaacs** [comment]
> About spaces, in general I prefer to define the behavior of whitespace to be explained outside the BNF grammar unless a space has a literal meaning.

In several cases, a space *does* have a literal meaning, so I think in this case it's worth specifying.

I *think* that this BNF will prevent you from trying to interpret a range like `"1.2.x "` as "the intersection of `"1.2.x"` and `""`, since simples can only be intersection-joined to other simples using a space.  Please correct me if I'm misreading that :)

I'm happy to add this grammar to the repo, but I think it might be overly disruptive to make `1.x.2` throw an error in this module.  Changes to semver behavior are very broad in their reach, since npm uses this module, and so I'd probably want to update it to print a warning instead, and then make it throw after a year or so of being in the wild.

**Comment by isaacs** [comment]
The `range.bnf` is now in the repository, and referenced in the docs.  Closing this, but I'm happy to reopen if you'd like to see a different approach.

**Comment by pkriens** [comment]
Thanks
