### ISSUE TITLE
Satisfies does not work as expected

### ISSUE THREAD

**Issue by yaycmyk** [npm/node-semver#142]
```js
var semver = require('semver');

semver.gt('6.0.0-pre', '0.5.0'); // true
semver.satisfies('6.0.0-pre', '>= 0.5.0'); // false
```

Although `6.0.0-pre` has a modifier, the base version still meets the requirement of the greater than / equal to and should pass the satisfaction test.

**Comment by excepttheweasel** [comment]
Should just add I noticed this when running `npm i` on a FreeBSD box with a freshly built node from source:

```
npm WARN engine chai@3.4.1: wanted: {"node":">= 0.4.0"} (current: {"node":"6.0.0-pre","npm":"3.3.12"})
npm WARN engine karma-chai-sinon@0.1.5: wanted: {"node":">=0.8"} (current: {"node":"6.0.0-pre","npm":"3.3.12"})
npm WARN engine karma@0.13.15: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"6.0.0-pre","npm":"3.3.12"})
```

**Comment by excepttheweasel** [comment]
@yaycmyk I believe this was a deliberate design decision: https://github.com/npm/node-semver#prerelease-tags

**Comment by yaycmyk** [comment]
Hmm. Not that this is necessarily the place to discuss this, but if a developer writes `>=`, that is a very open-ended assertion and it should be up to the dev to restrict the top-bound of that condition if they truly do not want to open the door to anything above a certain version.

I don't agree with leaving out versions with modifiers at all for straightforward `>|>=|<|<=` comparisons.

**Comment by yaycmyk** [comment]
Would appreciate your feedback on this @isaacs

**Comment by isaacs** [comment]
This is working as intended, and as documented.

Let's say that you require at least the features in the `0.5.0` version.  However, it's quite possible that `0.6.0-pre` *doesn't deliver those features*, because it is a pre-release version.  It might well be completely broken, in fact.

This is not a hypothetical scenario, it's a real thing that happened, and we went through an extensive period of figuring out the least-harmful path.  Re-opening the book on this is very disruptive, and not worth the cost.
