### ISSUE TITLE
Resolving prerelease dependencies

### ISSUE THREAD

**Issue by gilly3** [npm/node-semver#165]
When working on a feature, I publish builds with a prerelease identifier that matches the feature name.  I frequently have more than one feature in development at a time.  For example, my "foo" package could have two features, "knobs" and "buttons", published as foo@1.1.0-knobs.0 and foo@1.1.0-buttons.0 respectively.

I would like to add a dependency based on prerelease identifier.  But, if I add a dependency on ^1.1.0-buttons.0, and then `npm i`, I get 1.1.0-knobs.0.  Presumably, this is because knobs comes after buttons alphabetically.

Am I doing it wrong, or is this simply not yet supported?

**Comment by isaacs** [comment]
Yes, `^1.1.0-buttons.0` means `>=1.1.0-buttons.0 <2.0.0`.  Because you've used a prerelease identifier in the range with the `1.1.0` tuple, it'll allow other prerelease identifiers in that tuple.  (It would not match, for example, `1.1.1-switches.0`.)

There's no super slick single-operator-style way to say "Allow all prereleases in the `1.1.0-knobs.*` set", but you could of course do something like `>=1.1.0-knobs.0 <1.1.0-knobs.9999 || ^1.1.0` to allow (the first 10,000) prereleases in the `knobs` series, or the official 1.1.0, but no other prereleases.

**Comment by gilly3** [comment]
That's a fair workaround.  I'll start using it today.  Thanks.

However, I'd like to propose that the current semantics of choosing the latest build by comparing prerelease identifiers alphabetically is arbitrary, unexpected, and wrong.  In other words, `1.1.0-knobs.0` should not fall in the range of `>=1.1.0-buttons.0 <2.0.0`.  And neither should `1.1.0-buttons.0` fall in the range of `>=1.1.0-knobs.0 <2.0.0`.  I propose that ranges that include a prerelease identifier should only match versions that contain that prerelease identifier, or released builds.

In order to support defining ranges that span multiple prerelease identifiers (as may be desired if you are using identifiers like `alpha`, `beta`, and `rc`, for example), some syntax should be added to target prerelease identifiers.  Perhaps, something like `^1.1.0-^beta.0`.  Or `^1.1.0-^[alpha,beta,rc].0` (where the order of the prerelease identifiers in the set dictates their relative weight).

**Comment by isaacs** [comment]
So... are you suggesting that `>=1.1.0-buttons.0` would still allow `1.1.0-buttons.1`?  What about `1.1.0-buttons.0.and.knobs`?  (Maybe you see where I'm going with this.)

What we have now is a compromise that takes into account the relative rarity of using prerelease identifiers *at all*, and assuming that you're going to have a relatively small number of `2.0.0-whatever` type things before shipping the "real" `2.0.0`.  (And then, in practice, very quickly afterwards, you'll find some bugs and ship `2.0.1` and everyone will _actually_ use `2.0.3` a few weeks later.)

It's shocking to get prerelease versions if you're not opting into them explicitly, and since the "semantics" are so open-ended, it's essentially just "ever project does whatever", meaning that you have to know what's going on, and may as well just use a workaround like I suggested.  The more open-ended the semantics, the less valuable (or discoverable!) new syntax becomes.  Your proposal isn't bad, but I feel like it's not enough of a problem to justify adding more surface area.

I agree that alphabetically sorting them feels arbitrary, but idk, that's what the spec says, so that's what we do.  As the JavaScript community grows, it's entirely possible that more people will bump into this issue, of course, and it may make sense at some point.  For now, though, I'd like to avoid making the vocabulary of version ranges even more convoluted.

Thanks :)

**Comment by gilly3** [comment]
I just went and read the spec.  You are right, it does mandate a lexical comparison.  My proposal goes counter to the spec.  Oh, well.

**Comment by isaacs** [comment]
Well, your proposal is fine, it'd just mean that you add some range syntax to mean "use things with this prerelease tag, but not any other", I just am a bit skeptical of the utility of such a thing, because of how niche it is.

Your _expectation_ runs counter to the spec, of course ;)  And I have to agree that the spec is arbitrary in this regard, but probably any choice there would feel at least a little bit arbitrary.
