### ISSUE TITLE
Loose parse doesn't support x.y version

### ISSUE THREAD

**Issue by blanchma** [npm/node-semver#168]
semver.valid('2.0',true) and semver.valid('2.0',true) returns null.

If the whole point of disable strict is to support weird versions as 1.1.1.version, support something more usual as x.y. could be more useful. For example, mobile OS version come in x.y and not in semver compatible version. It would be great to parse them.

**Comment by isaacs** [comment]
@blanchma As you know, `2.0` is not a valid SemVer version.  SemVer versions always have at least 3 parts: major, minor, and patch.  It's not valid in "loose" mode, because it's not a SemVer version at all, it's a Range of versions, equivalent to `>=2.0.0 <2.1.0`.

I can appreciate that it would be useful to parse versions that are not SemVer versions.  However, the "semver" module is not designed to parse those versions, it's designed to parse versions that _are_ SemVer.  Perhaps you could write a function that converts it to SemVer before using this module, for instance by adding a `.0` to the string.

The point of disabling strict is not to support non-SemVer versions.  It is to support SemVer versions that were in widespread use in JavaScript and npm prior to the release of the much stricter and more clarified SemVer 2.0.0 specification.  npm and other programs needed to be able to interpret these versions that complied with pre-2.0.0 SemVer specifications, including many edge cases that had not yet been formally determined.  For example, until SemVer 2.0.0, `1.2.3foo` was allowed, because the `-` between prerelease and the main 3-ple was not required.
