### ISSUE TITLE
Comparing prerelease information does not seem to work correctly

### ISSUE THREAD

**Issue by sofuture** [npm/node-semver#182]
Specifically:

```
> semver.gt('1.5.1-rc.4', '1.5.1-rc.3-1-gf7e6a5c')
false
```

In my reading of the spec, this should be true.

From http://semver.org/#spec-item-9:
```
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-].
```

and from http://semver.org/#spec-item-11:
```
Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. 
```

These instructions make me think that the comparison should be between:

 1. `[1, 5, 1]` and `[1, 5, 1]` (==)
 1. `['rc', '4']` and `['rc', '3-1-gf7e6a5c']` (>)

Leading to `gt()` returning true.

Does this jive with your reading of the spec? I haven't delved into the code much yet, but will PR something if I'm not wildly offbase.

**Comment by isaacs** [comment]
The next sentence in that same section is the reason for this:

> Numeric identifiers always have lower precedence than non-numeric identifiers.

So, comparing a _numeric_ identifier with a _non-numeric_ identifier, the _non-numeric_ identifier is greater-than.

> identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.

Since `3-1-gf7e6a5c` has letters and hyphens, it's a "non-numeric identifier".  When compared with `4` (a numeric identifier) any non-numeric identifier like `alpha` or `rc` would be greater precedence, even if it _starts_ with a number.

This part here, though, is a bug in the spec, I think: 

> A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

since it's contradicted by everything else.

**Comment by sofuture** [comment]
Yep, you're right. The comparison is between numeric and non-numeric, and that reads pretty clearly. Thanks! :boom:
