### ISSUE TITLE
validRange doesn't format x-ranges correctly

### ISSUE THREAD

**Issue by edge** [npm/node-semver#183]
Currently `semver.validRange` doesn't correctly format unions containing full x-ranges.

```js
validRange('*') // good: '*'
validRange('* || 1.0.0') // bad: '||1.0.0'
validRange('* || *') // bad: '||'
```

I would recommend simply returning `'*'` if any of the components are `'*'`, like such:

```js
validRange('*') // '*'
validRange('* || 1.0.0') // '*'
validRange('* || *') // '*'
```

relevant code:
[semver.js#L709](https://github.com/npm/node-semver/blob/master/semver.js#L709)
[semver.js#L1107](https://github.com/npm/node-semver/blob/master/semver.js#L1107)

**Comment by isaacs** [comment]
But those aren't actually identical.

> I would recommend simply returning `*` if any of the components are `*`, like such:

Consider that `*` _doesn't_ match (by design) `1.0.0-prerelease`.  So, `* || 1.0.0-prerelease` is different than `*`.


> `validRange('* || 1.0.0') // bad: '||1.0.0'`

Since a blank range is equivalent to `*`, `||1.0.0-prerelease` actually _is_ identical to `* || 1.0.0-prerelease`.

I agree that it would be nice to omit identical ranges that exist between `||` characters.  Thus `*||*` would reduce to `||` and then merely a blank line, which would be replaced by `*` (which is there to support checks that do `if(validRange(...))` and expect `null` to be the only non-truthy return value).  We could also remove ranges in the set that don't have any prerelease parts if there's a `*`.  Patches welcome for those enhancements.

But what's there now is not semantically incorrect, and is working as intended.
