### ISSUE TITLE
inconsuistent prerelease tag comparation

### ISSUE THREAD

**Issue by easz** [npm/node-semver#231]
> Prerelease Tags
> ...
> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9

however if I try https://semver.npmjs.com/ with
package 'lodash' and range '>1.0.0-rc.1'
the 2.0.0 is matched!

do I understand wrong?
I though only prerelease from 1.0.0 will be matched.

**Comment by easz** [comment]
Ok, I tried package 'npm' with range '>1.5.0-alpha'
I got the idea...

**Comment by isaacs** [comment]
Prerelease versions can only match a range if the range includes a prerelease version of the same `MAJOR.MINOR.PATCH` tuple.

`2.0.0` would indeed match `>1.0.0-rc.1` (since it is not a prerelease version), and so would `1.0.0-rc.2` (since it is a prerelease from the same `1.0.0` tuple, and higher precedence than `1.0.0-rc.1`).  However, `2.0.0-rc.1` would not, because it is a prerelease from a different semver set.

This means that, effectively, prerelease versions are "opt-in", which prevents accidentally getting something that is not yet ready for prime time.
