### ISSUE TITLE
Using logical AND in version range

### ISSUE THREAD

**Issue by itaisteinherz** [npm/node-semver#273]
Since the module already supports using logical ORs (i.e. `||`) in version ranges, I think that it should also support using logical ANDs (i.e. `&&`).

**Comment by isaacs** [comment]
Whitespace is already a logical AND.  For example `>=6.1.0 <7.0.0` is "greater than or equal to 6.1.0 and less than 7.0.0".

I'd like to avoid adding any new semantics to the parsing logic unless absolutely necessary, since there are other SemVer implementations that aim for compatibility with this one.

**Comment by itaisteinherz** [comment]
I didn’t know that. Thanks!
