### ISSUE TITLE
[QUESTION] `semver.gt('1.0.0-rc10', '1.0.0-rc3')` returning false

### ISSUE THREAD

**Issue by agatakrajewska** [npm/node-semver#326]
Hi,

I'm using `semver@5.6.0`.

I'm running `semver.gt('1.0.0-rc10', '1.0.0-rc3')` and it's returning`false`, I'd expect the result to verify the `rcXX` suffix correctly but it's not.

Note, that I've ran semver.valid('1.0.0-rc10') before and these are valid `semver` versions.

Can anyone explain this behaviour or is it a bug?

Thank you!

**Comment by isaacs** [comment]
The prerelease section is a period-separated set of identifiers, which may be either ASCII alphanumeric strings, or numeric strings.  Strictly numeric strings are sorted in numeric order, and alphanumeric strings are sorted in ASCII order.  (Ie, numbers, then caps alphabetically, then lowercase alphabetically).

Because `rc10` and `rc3` are both alphanumeric strings, and `'1'` is a lower ASCII code than `'3'`, it sorts like it does.

```
> semver.gt('1.0.0-rc10', '1.0.0-rc3')
false
> semver.gt('1.0.0-rc.10', '1.0.0-rc.3')
true
> semver.gt('1.0.0-rc30', '1.0.0-rc3')
true
> semver.gt('1.0.0-rc30', '1.0.0-rc31')
false
> semver.gt('1.0.0-rc30', '1.0.0-rc4')
false
> semver.gt('1.0.0-rc.30', '1.0.0-rc.4')
true
```
