### ISSUE TITLE
[BUG] "1.0.0-2.0.0" passes semver.validRange check, yet returns false for semvers between that range. 

### ISSUE THREAD

**Issue by prodigga** [npm/node-semver#332]
### Current Behavior

* "1.0.0-2.0.0" passes semver.validRange check, yet won't detect versions within that range.

### Steps to Reproduce

* use "1.0.0-2.0.0" as range string. semver.validRange returns true. Check if 1.0.0 is in range. Returns false.
* Change string to "1.0.0 - 2.0.0". Now it works.

### Expected Behavior

* Should either return true when checking for versions between the specified range, or return false when checking to see if semver is valid. This seems like a very easy error to make when entering a semver range string, and my range parsing/validation code can't pick up the error.

**Comment by McSherry** [comment]
I'm not affiliated with node-semver, but I think I see the issue @prodigga.

The string `1.0.0-2.0.0` isn't just a valid range, but also a valid _version_ (`1.0.0` with pre-release identifiers `2`, `0`, `0`). Since it should parse to a valid version, it should be equivalent to the range `=1.0.0-2.0.0`.

**Comment by prodigga** [comment]
Oh I see, nice catch.
