### ISSUE TITLE
[QUESTION] Why doesn't semver.maxVersion exist?

### ISSUE THREAD

**Issue by ao10** [npm/node-semver#337]
Hi sorry if this is super obvious but I noticed `semver.minVersion` exists.

Why is there no counterpart to get the max version supported in a given range (i.e `semver.maxVersion`)?
Is there another way to retrieve the max version when only given a range?

Thanks

**Comment by alfredsgenkins** [comment]
I assume that's because when calculating the version, you need to take something as a starting point, for example, `0.0.0-0` is the smallest version - for sure. While if trying to get the maximum range the task becomes a little bit harder. I might be wrong. Currently trying to implement the same logic, as the current one seems broken in some cases.

**Comment by alfredsgenkins** [comment]
Also, ranges sometimes say `^0.0.0` then, what would you expect the maximum version to be? It is most likely impossible to define.

**Comment by justb** [comment]
> Also, ranges sometimes say `^0.0.0` then, what would you expect the maximum version to be? It is most likely impossible to define.

Return 'latest' maybe a feasible solution
