### ISSUE TITLE
[BUG] Range class returns different in > 7.3.2

### ISSUE THREAD

**Issue by Brianzchen** [npm/node-semver#370]
# What / Why

In semver `7.3.3` and `7.3.4`, `new Range('^v0.x.x')` returns different results compared to `7.3.2`. This broke users of the flow-typed project.

In the returned object, we expect to find two Comparators in `range.set` but in the newer versions it only returns one.

## > 7.3.2
```
Range {
  options: {},
  loose: false,
  includePrerelease: false,
  raw: '^v0.x.x',
  set: [ [ [Comparator] ] ],
  range: '<1.0.0-0'
}
```

## 7.3.2
```
Range {
  options: { loose: false, includePrerelease: false },
  loose: false,
  includePrerelease: false,
  raw: '^v0.x.x',
  set: [ [ [Comparator], [Comparator] ] ],
  range: '<1.0.0-0'
}
```

## References
https://github.com/flow-typed/flow-typed/issues/3988

**Comment by lukekarrys** [comment]
This was done by design, see https://github.com/npm/node-semver/issues/323#issuecomment-615967163 for more details.

**Comment by Brianzchen** [comment]
Thanks that's fair, I assumed as much though I just hoped there's a changelog outlining what has changed and why so we can make necessary adjustments on our end. Right now we've locked our versions as a result.

Could you help with this @lukekarrys ?

**Comment by lukekarrys** [comment]
@Brianzchen Yeah, I can definitely try and help! I read the issue you linked and I think I understand what broke, but can you help me understand the use case for looking at the comparators from `Range.set`? Are you operating on known ranges or user input (or something in between)?

There was some discussion in #323 about adding explicit methods to get the upper and lower bounds for a range, but was never implemented. Would an api like cover your use case? This has come up before (https://github.com/npm/node-semver/issues/343#issuecomment-1094173251) so I want to understand fully so that any new feature can be robust enough to accomplish the most use cases.
