### ISSUE TITLE
[BUG] diff prerelease changed between 7.3.8 and 7.5.4

### ISSUE THREAD

**Issue by foxriver76** [npm/node-semver#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

a diff between a non prerelease version like `5.5.0` and a prerelease version on the same patch now creates a `major` diff while it previously was `prerelease`

see https://github.com/npm/node-semver/pull/566/files

### Expected Behavior

It should be either `prerelease` or mention the breaking change it the changelog and why you think it should be that way. 

### Steps To Reproduce

```ts
import semverDiff from 'semver/functions/diff';

// is major
console.log(semverDiff('1.0.0-alpha.1', '1.0.0'));
```

### Environment

- npm: 
- Node: 16/18/20
- OS: windows/linux and mac (all on CI failing due to this problem)
- platform:

**Comment by ljharb** [comment]
`1.0.0-alpha.1` comes *before* `1.0.0`, and indeed could have a breaking change between the prerelease and `1.0.0`. I'm not sure it makes sense to have the arguments in the order you provided, and it should probably throw?

**Comment by foxriver76** [comment]
Yes, it was vice versa just on mobile. Okay if you are seeing it from that perspective this is true. I saw it from s perspective where the version string actually differs. Just not sure how many occurrences that broke. Probably not too mich if we are the only one expecting the issue, then I will adapt our code if it is intended.

**Comment by ljharb** [comment]
it looks like a bug, since `1.2.0-anything` and `1.2.0` diff by "prerelease"

**Comment by wraithgar** [comment]
No, the diff between `1.2.0-anything` and `1.2.0` is a minor.  This is admittedly a confusing part of the spec, and is why the bug existed previous to 7.5.4.

```
> semver.inc('1.1.9-pre', 'minor')
'1.2.0'
> semver.inc('1.1.9-pre', 'patch')
'1.1.9'
```

The inc you want is probably `pre` since that is what you're trying to increment.

```
> semver.inc('1.2.0-nightly.0', 'pre')
'1.2.0-nightly.1'
```

This subtlety is why `preminor` and `premajor` exist. Because if you were for instance trying to increment from `1.1.9` into a prerelease, you need to specify if it is the prerelease for a major, minor, or patch (the default is `pre` which is another confusing one because it goes back into the prerelease form of the *current* version, unless it's already in prerelease mode then it will increment the prerelease index as shown above).


```
> semver.inc('1.1.9', 'premajor')
'2.0.0-0'
> semver.inc('1.1.9', 'preminor')
'1.2.0-0'
> semver.inc('1.1.9', 'prepatch')
'1.1.10-0'
> semver.inc('1.1.9', 'pre')
'1.1.9-0'
```

**Comment by wraithgar** [comment]
Yes, exactly.  If the differ by anything more you'll get at the very least a `prepatch` which is the more specific diff between something like `1.2.9` and `1.2.10-0`

```javascript
> semver.inc('1.2.9', 'prerelease')
'1.2.10-0'
> semver.inc('1.2.9', 'prepatch')
'1.2.10-0'
> semver.diff('1.2.9', '1.2.10-0')
'prepatch'
```
